import jsPDF from 'jspdf';

interface AuditResult {
    score: number;
    domain: string;
    pagesScanned: number;
    issues: {
        cookies: {
            count: number;
            undeclared: number;
        };
        consentBanner: boolean;
        privacyPolicy: boolean;
        https: boolean;
        trackers: string[];
        legalMentions: boolean;
        dpoContact: boolean;
        dataDeleteLink: boolean;
        secureforms: boolean;
        optOutMechanism: boolean;
        ageVerification: boolean;
        cookiePolicy: boolean;
    };
    regulations: string[];
}

export function generatePDF(result: AuditResult): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PrivacyChecker', 20, 25);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Privacy Compliance Audit Report', 20, 35);

    y = 55;

    // Domain & Score
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(result.domain, 20, y);

    // Score badge
    const scoreColor = result.score >= 80 ? [34, 197, 94] : result.score >= 50 ? [234, 179, 8] : [239, 68, 68];
    doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.roundedRect(pageWidth - 50, y - 12, 35, 18, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text(`${result.score}%`, pageWidth - 42, y);

    y += 15;

    // Meta info
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString('fr-FR')} | Pages Scanned: ${result.pagesScanned} | Regulations: ${result.regulations.join(', ')}`, 20, y);

    y += 20;

    // Compliance Checks Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Compliance Checks', 20, y);
    y += 10;

    const checks = [
        { label: 'HTTPS Enabled', passed: result.issues.https },
        { label: 'Cookie Consent Banner', passed: result.issues.consentBanner },
        { label: 'Privacy Policy', passed: result.issues.privacyPolicy },
        { label: 'Cookie Policy', passed: result.issues.cookiePolicy },
        { label: 'Legal Mentions', passed: result.issues.legalMentions },
        { label: 'DPO Contact', passed: result.issues.dpoContact },
        { label: 'Data Deletion Option', passed: result.issues.dataDeleteLink },
        { label: 'Opt-out Mechanism', passed: result.issues.optOutMechanism },
        { label: 'Form Consent', passed: result.issues.secureforms },
        { label: 'Cookies Declared', passed: result.issues.cookies.undeclared === 0 },
    ];

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    checks.forEach((check) => {
        const icon = check.passed ? '✓' : '✗';
        const color = check.passed ? [34, 197, 94] : [239, 68, 68];

        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(icon, 20, y);
        doc.setTextColor(0, 0, 0);
        doc.text(check.label, 30, y);
        y += 7;
    });

    y += 10;

    // Cookie Summary
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Cookie Summary', 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Cookies Found: ${result.issues.cookies.count}`, 20, y);
    y += 7;
    doc.text(`Undeclared Cookies: ${result.issues.cookies.undeclared}`, 20, y);
    y += 7;

    if (result.issues.trackers.length > 0) {
        doc.text(`Third-Party Trackers: ${result.issues.trackers.join(', ')}`, 20, y);
        y += 7;
    }

    y += 15;

    // Footer
    doc.setFillColor(245, 245, 245);
    doc.rect(0, doc.internal.pageSize.getHeight() - 25, pageWidth, 25, 'F');

    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.text('Generated by PrivacyChecker - www.privacychecker.pro', 20, doc.internal.pageSize.getHeight() - 10);
    doc.text('This report is for informational purposes only.', pageWidth - 80, doc.internal.pageSize.getHeight() - 10);

    // Save
    doc.save(`privacycheck-${result.domain}-${new Date().toISOString().split('T')[0]}.pdf`);
}
