export interface Recommendation {
    title: string;
    description: string;
    steps: string[];
    priority: 'critical' | 'high' | 'medium' | 'low';
}

export const recommendations: Record<string, Recommendation> = {
    https: {
        title: 'Enable HTTPS',
        description: 'Your site is not using HTTPS, which is required for GDPR compliance and protects user data in transit.',
        steps: [
            'Get an SSL certificate (free with Let\'s Encrypt or your hosting provider)',
            'Install the certificate on your web server',
            'Configure automatic redirects from HTTP to HTTPS',
            'Update all internal links to use HTTPS',
            'Test your site to ensure all resources load over HTTPS',
        ],
        priority: 'high',
    },
    consentBanner: {
        title: 'Add Cookie Consent Banner',
        description: 'Your site needs a cookie consent banner to comply with GDPR and ePrivacy regulations.',
        steps: [
            'Choose a consent management platform (CMP) like OneTrust, Didomi, or open-source alternatives',
            'Configure the banner to block non-essential cookies until consent is given',
            'Categorize your cookies (necessary, analytics, marketing, preferences)',
            'Add clear accept/reject buttons - avoid dark patterns',
            'Store user preferences and respect their choices',
            'Test that cookies are actually blocked before consent',
        ],
        priority: 'high',
    },
    privacyPolicy: {
        title: 'Create a Privacy Policy',
        description: 'A privacy policy is legally required and must explain how you collect, use, and protect user data.',
        steps: [
            'List all data you collect (personal info, cookies, analytics, etc.)',
            'Explain why you collect each type of data (legal basis)',
            'Describe how long you retain the data',
            'List third parties with whom you share data',
            'Explain user rights (access, deletion, portability)',
            'Include contact information for data protection inquiries',
            'Keep the policy updated when your practices change',
        ],
        priority: 'high',
    },
    legalMentions: {
        title: 'Add Legal Mentions Page',
        description: 'Legal mentions (or imprint) identify who operates the website and are required by law in many countries.',
        steps: [
            'Create a "Legal Notice" or "Imprint" page',
            'Include company name and legal form',
            'Add registered address and contact information',
            'Include registration numbers (company registry, VAT)',
            'Name the person responsible for content',
            'Link to this page from your footer',
        ],
        priority: 'medium',
    },
    dpoContact: {
        title: 'Add DPO Contact Information',
        description: 'Users must be able to contact your Data Protection Officer or privacy team easily.',
        steps: [
            'Designate a DPO or privacy contact person',
            'Add their contact email in your privacy policy',
            'Create a dedicated privacy contact form or email (e.g., privacy@yoursite.com)',
            'Ensure someone monitors and responds to privacy inquiries within 30 days',
        ],
        priority: 'medium',
    },
    dataDeleteLink: {
        title: 'Add Data Deletion Option',
        description: 'GDPR requires you to allow users to request deletion of their personal data.',
        steps: [
            'Add a "Delete My Data" link or form accessible to users',
            'Create a process to verify user identity before deletion',
            'Implement the actual data deletion in your systems',
            'Keep a log of deletion requests for compliance',
            'Respond to deletion requests within 30 days',
            'Inform third parties to also delete the data',
        ],
        priority: 'high',
    },
    optOutMechanism: {
        title: 'Implement Opt-Out Mechanism',
        description: 'Users must be able to opt out of marketing communications and non-essential data processing.',
        steps: [
            'Add unsubscribe links to all marketing emails',
            'Create a preferences page where users can manage consent',
            'Honor opt-out requests immediately',
            'Keep a suppression list to prevent re-adding opted-out users',
            'Provide opt-out for analytics if using personal data',
        ],
        priority: 'medium',
    },
    secureforms: {
        title: 'Secure Your Forms',
        description: 'Forms collecting personal data must be transmitted securely and validated properly.',
        steps: [
            'Ensure all forms submit over HTTPS',
            'Add CSRF protection tokens to forms',
            'Validate and sanitize all input server-side',
            'Only collect necessary data (data minimization)',
            'Add privacy notices near form submit buttons',
            'Encrypt sensitive data at rest in your database',
        ],
        priority: 'medium',
    },
    cookiePolicy: {
        title: 'Create Cookie Policy',
        description: 'A dedicated cookie policy explains what cookies you use and why.',
        steps: [
            'Create a dedicated cookie policy page',
            'List all cookies used on your site',
            'Categorize cookies (necessary, analytics, marketing, etc.)',
            'Explain the purpose of each cookie',
            'Include cookie duration and provider',
            'Explain how users can manage cookie preferences',
            'Link to the cookie policy from your consent banner',
        ],
        priority: 'medium',
    },
    ageVerification: {
        title: 'Consider Age Verification',
        description: 'If your service targets users under 16, you may need parental consent mechanisms.',
        steps: [
            'Determine if your service appeals to minors',
            'If so, implement age verification at registration',
            'For users under 16, require parental consent',
            'Consider using age-appropriate privacy notices',
            'Review COPPA requirements if operating in the US',
        ],
        priority: 'low',
    },
    // Consent Behavior recommendations
    darkPatterns: {
        title: 'Remove Dark Patterns from Consent Banner',
        description: 'Your consent banner uses manipulative design patterns that violate GDPR Article 7 (conditions for consent).',
        steps: [
            'Make the "Reject" button as visible and prominent as the "Accept" button',
            'Use neutral language - avoid guilt-tripping ("I don\'t care about privacy")',
            'Do not pre-check any non-essential cookie categories',
            'Remove cookie walls that block content access',
            'Allow closing the banner without making a choice',
            'Use the same number of clicks to reject as to accept',
            'Test your banner on mobile devices for accessibility',
        ],
        priority: 'high',
    },
    preConsentCookies: {
        title: 'Fix Pre-Consent Cookie Loading',
        description: 'Your site loads tracking cookies/scripts before obtaining user consent, which violates GDPR.',
        steps: [
            'Audit all third-party scripts (analytics, marketing pixels, etc.)',
            'Configure your CMP to block scripts until consent is given',
            'Use Google Tag Manager Consent Mode or similar for Google services',
            'Move script tags below the consent initialization code',
            'Use conditional loading: only execute scripts after consent',
            'Test by clearing cookies and verifying no trackers fire before consent',
            'Consider server-side tracking for privacy-compliant analytics',
        ],
        priority: 'high',
    },
    missingRejectButton: {
        title: 'Add Clear Reject Button to Consent Banner',
        description: 'Your consent banner does not have a clearly visible option to reject non-essential cookies.',
        steps: [
            'Add a "Reject All" or "Only Essential" button to your banner',
            'Place it at the same level and prominence as "Accept All"',
            'Avoid hiding reject options behind "Manage Preferences"',
            'Use clear, unambiguous text (not "Maybe later" or "Customize")',
            'Ensure one click is enough to reject all non-essential cookies',
            'Test that clicking reject actually blocks non-essential cookies',
        ],
        priority: 'high',
    },
    confirmShaming: {
        title: 'Remove Confirm Shaming Language',
        description: 'Your consent banner uses guilt-inducing language to manipulate users into accepting cookies.',
        steps: [
            'Replace manipulative text with neutral options',
            'Good: "Reject" or "Only necessary cookies"',
            'Bad: "No, I don\'t care about my experience" or "I\'ll miss out"',
            'Avoid emotional or fear-based language',
            'Let the choice speak for itself without commentary',
            'Review EDPB guidelines on valid consent',
        ],
        priority: 'medium',
    },
    preCheckedBoxes: {
        title: 'Uncheck Non-Essential Cookie Categories',
        description: 'Your consent settings have non-essential cookies pre-checked, which creates invalid consent under GDPR.',
        steps: [
            'Set all non-essential categories (analytics, marketing, preferences) to OFF by default',
            'Only "Strictly Necessary" cookies can be pre-enabled',
            'Let users actively opt-in to each category',
            'Save unchecked state as the default preference',
            'Test the consent flow from a fresh browser session',
        ],
        priority: 'high',
    },
    // Privacy Policy AI Analysis recommendations
    policyLegalBasis: {
        title: 'Specify Legal Basis for Data Processing',
        description: 'Your privacy policy does not clearly specify the legal basis for processing personal data under GDPR Article 6.',
        steps: [
            'Identify all types of personal data you collect',
            'For each data type, specify one of the six legal bases: consent, contract, legal obligation, vital interests, public interest, or legitimate interest',
            'Explain why you rely on each legal basis',
            'If using legitimate interest, document your balancing test',
            'Add a section titled "Legal Basis for Processing" to your privacy policy',
            'Reference GDPR Article 6 explicitly for transparency',
        ],
        priority: 'high',
    },
    policyDataRetention: {
        title: 'Add Data Retention Policy',
        description: 'Your privacy policy lacks clear information about how long you retain personal data.',
        steps: [
            'Audit all data categories you store',
            'Define retention periods for each category (e.g., "account data: until account deletion + 30 days")',
            'Add a "Data Retention" section to your privacy policy',
            'Specify what happens when the retention period expires (deletion, anonymization)',
            'Include retention periods required by law (e.g., financial records, tax documents)',
            'Explain the criteria used to determine retention periods',
        ],
        priority: 'high',
    },
    policyUserRights: {
        title: 'Document All User Rights',
        description: 'Your privacy policy does not fully explain all GDPR user rights (Articles 15-22).',
        steps: [
            'Add a "Your Rights" section to your privacy policy',
            'Include: Right of Access (Art. 15) - users can request a copy of their data',
            'Include: Right to Rectification (Art. 16) - users can correct inaccurate data',
            'Include: Right to Erasure (Art. 17) - the "right to be forgotten"',
            'Include: Right to Data Portability (Art. 20) - users can receive data in machine-readable format',
            'Include: Right to Object (Art. 21) - users can object to processing',
            'Explain how users can exercise each right (email, form, etc.)',
        ],
        priority: 'high',
    },
    policyContactInfo: {
        title: 'Add Privacy Contact Information',
        description: 'Your privacy policy lacks adequate contact information for privacy inquiries.',
        steps: [
            'Designate a Data Protection Officer (DPO) or privacy contact person',
            'Add a dedicated privacy email address (e.g., privacy@yoursite.com)',
            'Include your company\'s physical address',
            'Mention the relevant supervisory authority (e.g., CNIL, ICO)',
            'Explain users\' right to lodge a complaint with the supervisory authority',
            'Ensure someone monitors and responds to privacy inquiries within 30 days',
        ],
        priority: 'medium',
    },
    policyThirdParty: {
        title: 'Disclose Third-Party Data Sharing',
        description: 'Your privacy policy does not adequately disclose who you share data with.',
        steps: [
            'List all categories of third parties who receive user data',
            'Name specific providers where possible (Google Analytics, Stripe, etc.)',
            'Explain the purpose of each data sharing relationship',
            'Indicate whether third parties are processors or controllers',
            'Link to third-party privacy policies where appropriate',
            'Explain how users can opt out of third-party data sharing where applicable',
        ],
        priority: 'high',
    },
    policyInternationalTransfers: {
        title: 'Document International Data Transfers',
        description: 'Your privacy policy does not explain international data transfers and safeguards.',
        steps: [
            'Identify if data is transferred outside the EU/EEA',
            'List the countries where data is transferred',
            'Specify the legal mechanism used (SCCs, adequacy decision, BCRs)',
            'If using US providers, mention the EU-US Data Privacy Framework if applicable',
            'Add an "International Transfers" section to your privacy policy',
            'Explain how users can obtain a copy of the transfer safeguards',
        ],
        priority: 'medium',
    },
    // Dark Patterns recommendations
    darkPatternConfirmshaming: {
        title: 'Remove Confirmshaming Language',
        description: 'Your site uses guilt-tripping language to manipulate user decisions (e.g., "No thanks, I hate saving money").',
        steps: [
            'Identify all buttons and links that decline offers or opt-out',
            'Replace manipulative language with neutral options (e.g., "No thanks" or "Skip")',
            'Avoid negative self-statements (e.g., "I don\'t care about my privacy")',
            'Remove sad emojis or guilt-inducing imagery from decline options',
            'Ensure reject/decline options are written in respectful, neutral language',
            'Test all user flows to ensure no confirmshaming remains',
        ],
        priority: 'high',
    },
    darkPatternPreSelection: {
        title: 'Uncheck Pre-Selected Consent Boxes',
        description: 'Pre-checked checkboxes for marketing or data sharing violate GDPR consent requirements.',
        steps: [
            'Audit all forms for pre-checked checkboxes related to marketing or data sharing',
            'Remove the "checked" attribute from these inputs',
            'Ensure newsletter and marketing opt-ins require explicit user action',
            'Set all consent toggles to OFF by default',
            'Keep only strictly necessary cookies enabled by default',
            'Document the changes for compliance records',
        ],
        priority: 'critical',
    },
    darkPatternRoachMotel: {
        title: 'Simplify Account Deletion',
        description: 'Users find it easy to sign up but difficult to cancel or delete their accounts.',
        steps: [
            'Add a self-service account deletion option in account settings',
            'Do not require users to call or email to cancel',
            'Limit cancellation to 2-3 clicks maximum',
            'Remove mandatory surveys before cancellation',
            'Process deletion requests within 30 days (GDPR requirement)',
            'Provide clear confirmation of deletion completion',
        ],
        priority: 'high',
    },
    darkPatternMisdirection: {
        title: 'Balance Accept/Reject Button Design',
        description: 'Your consent interface gives visual priority to the "Accept" option over "Reject".',
        steps: [
            'Make Accept and Reject buttons the same size',
            'Use the same color intensity for both options (or neutral colors for both)',
            'Place both buttons at the same level, not one hidden or smaller',
            'Avoid using bright colors for Accept and gray/faded for Reject',
            'Ensure equal visual weight in font size and styling',
            'Test with users to ensure no bias in the interface',
        ],
        priority: 'medium',
    },
    darkPatternHiddenInfo: {
        title: 'Make Privacy Information Visible',
        description: 'Important privacy-related information is hidden or displayed with low contrast.',
        steps: [
            'Ensure all privacy notices meet WCAG contrast requirements (4.5:1 minimum)',
            'Use font sizes of at least 12px for important privacy text',
            'Do not hide unsubscribe or opt-out links with display:none',
            'Avoid extremely small scroll containers for terms and conditions',
            'Place privacy links prominently in page footer and relevant forms',
            'Test readability across different devices and browsers',
        ],
        priority: 'high',
    },
};

export const getRecommendation = (issueKey: string): Recommendation | null => {
    return recommendations[issueKey] || null;
};
