// Vendor Privacy Risk Database
// Score: 1 (low risk) to 10 (high risk)
// Based on: Data transfer jurisdiction, data retention, transparency, past incidents

export interface VendorRisk {
    name: string;
    category: 'analytics' | 'advertising' | 'social' | 'cdn' | 'payment' | 'other';
    riskScore: number; // 1-10
    jurisdiction: string;
    dataTransfer: 'EU' | 'US' | 'CN' | 'Other';
    concerns: string[];
    gdprCompliant: boolean;
    privacyPolicyUrl: string;
}

export const vendorRiskDatabase: Record<string, VendorRisk> = {
    // === ANALYTICS ===
    'google-analytics': {
        name: 'Google Analytics',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Third-party sharing', 'Long retention'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'google-tag-manager': {
        name: 'Google Tag Manager',
        category: 'analytics',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Indirect data collection'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'hotjar': {
        name: 'Hotjar',
        category: 'analytics',
        riskScore: 4,
        jurisdiction: 'Malta (EU)',
        dataTransfer: 'EU',
        concerns: ['Session recording', 'Behavior tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.hotjar.com/privacy/',
    },
    'mixpanel': {
        name: 'Mixpanel',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'User profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://mixpanel.com/legal/privacy-policy/',
    },
    'amplitude': {
        name: 'Amplitude',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Behavioral analytics'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://amplitude.com/privacy',
    },
    'segment': {
        name: 'Segment',
        category: 'analytics',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Data broker', 'Third-party sharing'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://segment.com/legal/privacy/',
    },
    'clarity': {
        name: 'Microsoft Clarity',
        category: 'analytics',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Session recording'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://privacy.microsoft.com/',
    },
    'heap': {
        name: 'Heap Analytics',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Auto-capture all events'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://heap.io/privacy',
    },
    'plausible': {
        name: 'Plausible Analytics',
        category: 'analytics',
        riskScore: 1,
        jurisdiction: 'Estonia (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://plausible.io/privacy',
    },
    'matomo': {
        name: 'Matomo',
        category: 'analytics',
        riskScore: 1,
        jurisdiction: 'Self-hosted / EU',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://matomo.org/privacy/',
    },
    'fathom': {
        name: 'Fathom Analytics',
        category: 'analytics',
        riskScore: 1,
        jurisdiction: 'Canada',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://usefathom.com/privacy',
    },

    // === ADVERTISING ===
    'google-ads': {
        name: 'Google Ads',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Cross-site tracking', 'Profiling', 'Third-party sharing'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'facebook-pixel': {
        name: 'Facebook/Meta Pixel',
        category: 'advertising',
        riskScore: 8,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Cross-site tracking', 'Shadow profiles', 'Past data breaches'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.facebook.com/privacy/policy/',
    },
    'tiktok-pixel': {
        name: 'TikTok Pixel',
        category: 'advertising',
        riskScore: 9,
        jurisdiction: 'China/Singapore',
        dataTransfer: 'CN',
        concerns: ['Chinese jurisdiction', 'Government access concerns', 'Opaque data practices', 'Cross-site tracking'],
        gdprCompliant: false,
        privacyPolicyUrl: 'https://www.tiktok.com/legal/privacy-policy',
    },
    'linkedin-insight': {
        name: 'LinkedIn Insight Tag',
        category: 'advertising',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Professional profiling', 'Microsoft ownership'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.linkedin.com/legal/privacy-policy',
    },
    'twitter-pixel': {
        name: 'Twitter/X Pixel',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Cross-site tracking', 'Uncertain data governance'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://twitter.com/en/privacy',
    },
    'pinterest-tag': {
        name: 'Pinterest Tag',
        category: 'advertising',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Interest profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policy.pinterest.com/privacy-policy',
    },
    'snapchat-pixel': {
        name: 'Snapchat Pixel',
        category: 'advertising',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Audience targeting'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://snap.com/en-US/privacy/privacy-policy',
    },
    'criteo': {
        name: 'Criteo',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: ['Retargeting', 'Cross-site tracking', 'Extensive profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.criteo.com/privacy/',
    },
    'taboola': {
        name: 'Taboola',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'Israel',
        dataTransfer: 'Other',
        concerns: ['Content recommendation profiling', 'Cross-site tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.taboola.com/policies/privacy-policy',
    },
    'outbrain': {
        name: 'Outbrain',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Content recommendation profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.outbrain.com/privacy/',
    },
    'hubspot': {
        name: 'HubSpot',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'CRM tracking', 'Email tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://legal.hubspot.com/privacy-policy',
    },

    // === SOCIAL ===
    'facebook-sdk': {
        name: 'Facebook SDK',
        category: 'social',
        riskScore: 8,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Social graph access', 'Past data breaches'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.facebook.com/privacy/policy/',
    },
    'instagram-embed': {
        name: 'Instagram Embed',
        category: 'social',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Tracking via embeds'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.facebook.com/privacy/policy/',
    },
    'youtube-embed': {
        name: 'YouTube Embed',
        category: 'social',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Google ecosystem'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'twitter-embed': {
        name: 'Twitter/X Embed',
        category: 'social',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Tracking via embeds'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://twitter.com/en/privacy',
    },
    'tiktok-embed': {
        name: 'TikTok Embed',
        category: 'social',
        riskScore: 9,
        jurisdiction: 'China/Singapore',
        dataTransfer: 'CN',
        concerns: ['Chinese jurisdiction', 'Government access concerns', 'Tracking via embeds'],
        gdprCompliant: false,
        privacyPolicyUrl: 'https://www.tiktok.com/legal/privacy-policy',
    },

    // === CDN / INFRASTRUCTURE ===
    'cloudflare': {
        name: 'Cloudflare',
        category: 'cdn',
        riskScore: 2,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.cloudflare.com/privacypolicy/',
    },
    'google-fonts': {
        name: 'Google Fonts',
        category: 'cdn',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'IP logging', 'GDPR fine precedent in Germany'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'jsdelivr': {
        name: 'jsDelivr',
        category: 'cdn',
        riskScore: 2,
        jurisdiction: 'Poland (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.jsdelivr.com/terms/privacy-policy',
    },
    'unpkg': {
        name: 'unpkg',
        category: 'cdn',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.cloudflare.com/privacypolicy/',
    },

    // === PAYMENT ===
    'stripe': {
        name: 'Stripe',
        category: 'payment',
        riskScore: 2,
        jurisdiction: 'USA/Ireland',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://stripe.com/privacy',
    },
    'paypal': {
        name: 'PayPal',
        category: 'payment',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.paypal.com/privacy/full',
    },

    // === OTHER ===
    'intercom': {
        name: 'Intercom',
        category: 'other',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Chat history retention'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.intercom.com/legal/privacy',
    },
    'zendesk': {
        name: 'Zendesk',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.zendesk.com/company/agreements-and-terms/privacy-notice/',
    },
    'drift': {
        name: 'Drift',
        category: 'other',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Chatbot tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.drift.com/privacy/',
    },
    'freshchat': {
        name: 'Freshchat',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA/India',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.freshworks.com/privacy/',
    },
    'recaptcha': {
        name: 'Google reCAPTCHA',
        category: 'other',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Behavioral fingerprinting', 'Unclear data use'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://policies.google.com/privacy',
    },
    'hcaptcha': {
        name: 'hCaptcha',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.hcaptcha.com/privacy',
    },
    'sentry': {
        name: 'Sentry',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Error data may contain PII'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://sentry.io/privacy/',
    },
    'logrocket': {
        name: 'LogRocket',
        category: 'other',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Session replay', 'May capture sensitive data'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://logrocket.com/privacy/',
    },
    'fullstory': {
        name: 'FullStory',
        category: 'other',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Session replay', 'May capture sensitive data'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.fullstory.com/legal/privacy/',
    },

    // === EMAIL MARKETING ===
    'mailchimp': {
        name: 'Mailchimp',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Email tracking pixels', 'Subscriber data'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://mailchimp.com/legal/privacy/',
    },
    'klaviyo': {
        name: 'Klaviyo',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Email tracking', 'Customer profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.klaviyo.com/legal/privacy',
    },
    'sendgrid': {
        name: 'SendGrid (Twilio)',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Email delivery tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.twilio.com/legal/privacy',
    },
    'brevo': {
        name: 'Brevo (Sendinblue)',
        category: 'advertising',
        riskScore: 3,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: ['Email tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.brevo.com/legal/privacypolicy/',
    },
    'mailgun': {
        name: 'Mailgun',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.mailgun.com/legal/privacy-policy/',
    },
    'convertkit': {
        name: 'ConvertKit',
        category: 'advertising',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Email tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://convertkit.com/privacy',
    },
    'activecampaign': {
        name: 'ActiveCampaign',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Email tracking', 'CRM'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.activecampaign.com/legal/privacy-policy',
    },

    // === E-COMMERCE ===
    'shopify': {
        name: 'Shopify',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'Canada',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Purchase tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.shopify.com/legal/privacy',
    },
    'woocommerce': {
        name: 'WooCommerce',
        category: 'other',
        riskScore: 2,
        jurisdiction: 'Self-hosted',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://automattic.com/privacy/',
    },
    'bigcommerce': {
        name: 'BigCommerce',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.bigcommerce.com/privacy/',
    },

    // === A/B TESTING ===
    'optimizely': {
        name: 'Optimizely',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Behavioral experiments'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.optimizely.com/legal/privacy-policy/',
    },
    'vwo': {
        name: 'VWO',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'India',
        dataTransfer: 'Other',
        concerns: ['Session recording', 'A/B testing'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://vwo.com/privacy-policy/',
    },
    'abtasty': {
        name: 'AB Tasty',
        category: 'analytics',
        riskScore: 3,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: ['Behavioral experiments'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.abtasty.com/privacy-policy/',
    },

    // === PUSH NOTIFICATIONS ===
    'onesignal': {
        name: 'OneSignal',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Push notification tracking', 'Device fingerprinting'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://onesignal.com/privacy_policy',
    },
    'firebase': {
        name: 'Firebase (Google)',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Google ecosystem', 'Analytics'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://firebase.google.com/support/privacy',
    },
    'pusher': {
        name: 'Pusher',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'UK',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://pusher.com/legal/privacy-policy',
    },

    // === CONSENT MANAGEMENT ===
    'cookiebot': {
        name: 'Cookiebot',
        category: 'other',
        riskScore: 2,
        jurisdiction: 'Denmark (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.cookiebot.com/en/privacy-policy/',
    },
    'onetrust': {
        name: 'OneTrust',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.onetrust.com/privacy/',
    },
    'didomi': {
        name: 'Didomi',
        category: 'other',
        riskScore: 2,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.didomi.io/privacy-policy',
    },
    'trustarc': {
        name: 'TrustArc',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://trustarc.com/privacy-policy/',
    },
    'axeptio': {
        name: 'Axeptio',
        category: 'other',
        riskScore: 1,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.axeptio.eu/en/privacy',
    },

    // === VIDEO ===
    'vimeo': {
        name: 'Vimeo',
        category: 'social',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Video analytics'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://vimeo.com/privacy',
    },
    'wistia': {
        name: 'Wistia',
        category: 'analytics',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Video engagement tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://wistia.com/privacy',
    },
    'jwplayer': {
        name: 'JW Player',
        category: 'social',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Video analytics'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.jwplayer.com/privacy/',
    },
    'brightcove': {
        name: 'Brightcove',
        category: 'social',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Video analytics'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.brightcove.com/en/legal/privacy/',
    },

    // === REVIEWS ===
    'trustpilot': {
        name: 'Trustpilot',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'Denmark (EU)',
        dataTransfer: 'EU',
        concerns: ['User review data'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://legal.trustpilot.com/for-businesses/privacy-policy',
    },
    'yotpo': {
        name: 'Yotpo',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'Israel',
        dataTransfer: 'Other',
        concerns: ['Customer review tracking', 'Email marketing'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.yotpo.com/privacy-policy/',
    },
    'judge-me': {
        name: 'Judge.me',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://judge.me/privacy',
    },
    'bazaarvoice': {
        name: 'Bazaarvoice',
        category: 'advertising',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Consumer profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.bazaarvoice.com/legal/privacy-policy/',
    },

    // === SUPPORT / CHAT ===
    'crisp': {
        name: 'Crisp',
        category: 'other',
        riskScore: 2,
        jurisdiction: 'France (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://crisp.chat/en/privacy/',
    },
    'livechat': {
        name: 'LiveChat',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'Poland (EU)',
        dataTransfer: 'EU',
        concerns: ['Chat history retention'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.livechat.com/legal/privacy-policy/',
    },
    'tidio': {
        name: 'Tidio',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'Poland (EU)',
        dataTransfer: 'EU',
        concerns: ['Chat history'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.tidio.com/privacy-policy/',
    },
    'tawk': {
        name: 'Tawk.to',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Chat history'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.tawk.to/privacy-policy/',
    },
    'freshdesk': {
        name: 'Freshdesk',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA/India',
        dataTransfer: 'US',
        concerns: ['US data transfer'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.freshworks.com/privacy/',
    },

    // === CRM / CDP ===
    'salesforce': {
        name: 'Salesforce',
        category: 'other',
        riskScore: 4,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Customer data platform'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.salesforce.com/company/privacy/',
    },
    'pipedrive': {
        name: 'Pipedrive',
        category: 'other',
        riskScore: 3,
        jurisdiction: 'Estonia (EU)',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.pipedrive.com/en/privacy',
    },
    'mparticle': {
        name: 'mParticle',
        category: 'analytics',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Customer data platform', 'Cross-device tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.mparticle.com/privacy',
    },
    'tealium': {
        name: 'Tealium',
        category: 'analytics',
        riskScore: 6,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Tag management', 'Customer data platform'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://tealium.com/privacy-policy/',
    },

    // === RETARGETING / DSP ===
    'adroll': {
        name: 'AdRoll (NextRoll)',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Cross-site retargeting', 'Profiling'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.nextroll.com/privacy',
    },
    'thetradedesk': {
        name: 'The Trade Desk',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Programmatic advertising', 'User ID tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.thetradedesk.com/general/privacy-policy',
    },
    'mediamath': {
        name: 'MediaMath',
        category: 'advertising',
        riskScore: 7,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Programmatic advertising'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.mediamath.com/privacy-policy/',
    },

    // === ANALYTICS (MORE) ===
    'posthog': {
        name: 'PostHog',
        category: 'analytics',
        riskScore: 2,
        jurisdiction: 'USA/EU',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://posthog.com/privacy',
    },
    'countly': {
        name: 'Countly',
        category: 'analytics',
        riskScore: 2,
        jurisdiction: 'UK',
        dataTransfer: 'EU',
        concerns: [],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://count.ly/legal/privacy-policy',
    },
    'pendo': {
        name: 'Pendo',
        category: 'analytics',
        riskScore: 5,
        jurisdiction: 'USA',
        dataTransfer: 'US',
        concerns: ['US data transfer', 'Product analytics', 'User tracking'],
        gdprCompliant: true,
        privacyPolicyUrl: 'https://www.pendo.io/privacy-policy/',
    },
};

// Pattern matching for detecting vendors in scripts/URLs
export const vendorPatterns: { pattern: RegExp; vendor: string }[] = [
    // Analytics
    { pattern: /google-analytics\.com|googletagmanager\.com\/gtag/i, vendor: 'google-analytics' },
    { pattern: /googletagmanager\.com\/gtm/i, vendor: 'google-tag-manager' },
    { pattern: /static\.hotjar\.com|hotjar\.com\/c\/hotjar/i, vendor: 'hotjar' },
    { pattern: /cdn\.mxpnl\.com|mixpanel\.com/i, vendor: 'mixpanel' },
    { pattern: /cdn\.amplitude\.com|amplitude\.com/i, vendor: 'amplitude' },
    { pattern: /cdn\.segment\.com|segment\.io/i, vendor: 'segment' },
    { pattern: /clarity\.ms/i, vendor: 'clarity' },
    { pattern: /heap\.io|heapanalytics\.com/i, vendor: 'heap' },
    { pattern: /plausible\.io/i, vendor: 'plausible' },
    { pattern: /matomo\.(org|cloud)|piwik\./i, vendor: 'matomo' },
    { pattern: /cdn\.usefathom\.com/i, vendor: 'fathom' },
    { pattern: /cdn\.optimizely\.com|optimizely\.com/i, vendor: 'optimizely' },
    { pattern: /dev\.visualwebsiteoptimizer\.com|vwo\.com/i, vendor: 'vwo' },
    { pattern: /try\.abtasty\.com|abtasty\.com/i, vendor: 'abtasty' },
    { pattern: /app\.posthog\.com|posthog\.com\/static/i, vendor: 'posthog' },
    { pattern: /count\.ly|countly/i, vendor: 'countly' },
    { pattern: /cdn\.pendo\.io|pendo\.io/i, vendor: 'pendo' },
    { pattern: /fast\.wistia\.com|wistia\.com/i, vendor: 'wistia' },
    { pattern: /mparticle\.com/i, vendor: 'mparticle' },
    { pattern: /tags\.tiqcdn\.com|tealium\.com|tealiumiq\.com/i, vendor: 'tealium' },
    { pattern: /firebaseapp\.com|firebase\.google\.com|firebasestorage\.googleapis\.com/i, vendor: 'firebase' },

    // Advertising
    { pattern: /googleadservices\.com|googlesyndication\.com|doubleclick\.net/i, vendor: 'google-ads' },
    { pattern: /connect\.facebook\.net.*fbevents|facebook\.com\/tr/i, vendor: 'facebook-pixel' },
    { pattern: /analytics\.tiktok\.com|tiktok\.com\/i18n\/pixel/i, vendor: 'tiktok-pixel' },
    { pattern: /snap\.licdn\.com|linkedin\.com\/px|platform\.linkedin\.com\/in\.js/i, vendor: 'linkedin-insight' },
    { pattern: /static\.ads-twitter\.com|t\.co\/i\/adsct/i, vendor: 'twitter-pixel' },
    { pattern: /pintrk|assets\.pinterest\.com/i, vendor: 'pinterest-tag' },
    { pattern: /sc-static\.net|snapchat\.com.*scevent/i, vendor: 'snapchat-pixel' },
    { pattern: /static\.criteo\.net|criteo\.com/i, vendor: 'criteo' },
    { pattern: /cdn\.taboola\.com/i, vendor: 'taboola' },
    { pattern: /outbrain\.com/i, vendor: 'outbrain' },
    { pattern: /js\.hs-scripts\.com|hubspot\.(com|net)/i, vendor: 'hubspot' },
    { pattern: /s\.adroll\.com|adroll\.com/i, vendor: 'adroll' },
    { pattern: /js\.adsrvr\.org|thetradedesk\.com/i, vendor: 'thetradedesk' },
    { pattern: /pixel\.mathtag\.com|mediamath\.com/i, vendor: 'mediamath' },

    // Email Marketing
    { pattern: /chimpstatic\.com|mailchimp\.com|list-manage\.com/i, vendor: 'mailchimp' },
    { pattern: /static\.klaviyo\.com|klaviyo\.com/i, vendor: 'klaviyo' },
    { pattern: /sendgrid\.(com|net)/i, vendor: 'sendgrid' },
    { pattern: /sibautomation\.com|brevo\.com|sendinblue\.com/i, vendor: 'brevo' },
    { pattern: /mailgun\.(com|org)/i, vendor: 'mailgun' },
    { pattern: /convertkit\.com|convertkit-mail/i, vendor: 'convertkit' },
    { pattern: /trackcmp\.net|activecampaign\.com/i, vendor: 'activecampaign' },

    // Social
    { pattern: /connect\.facebook\.net(?!.*fbevents)/i, vendor: 'facebook-sdk' },
    { pattern: /instagram\.com\/embed/i, vendor: 'instagram-embed' },
    { pattern: /youtube\.com\/embed|youtube-nocookie\.com/i, vendor: 'youtube-embed' },
    { pattern: /platform\.twitter\.com/i, vendor: 'twitter-embed' },
    { pattern: /tiktok\.com\/embed/i, vendor: 'tiktok-embed' },
    { pattern: /player\.vimeo\.com|vimeocdn\.com/i, vendor: 'vimeo' },
    { pattern: /jwpsrv\.com|jwpcdn\.com|jwplayer\.com/i, vendor: 'jwplayer' },
    { pattern: /players\.brightcove\.net|brightcove\.com/i, vendor: 'brightcove' },

    // CDN - More precise patterns to avoid false positives
    { pattern: /cdnjs\.cloudflare\.com|cloudflare-ipfs\.com|challenges\.cloudflare\.com/i, vendor: 'cloudflare' },
    { pattern: /fonts\.googleapis\.com|fonts\.gstatic\.com/i, vendor: 'google-fonts' },
    { pattern: /cdn\.jsdelivr\.net/i, vendor: 'jsdelivr' },
    { pattern: /unpkg\.com/i, vendor: 'unpkg' },

    // E-commerce
    { pattern: /cdn\.shopify\.com|shopifycdn\.com/i, vendor: 'shopify' },
    { pattern: /woocommerce/i, vendor: 'woocommerce' },
    { pattern: /bigcommerce\.com/i, vendor: 'bigcommerce' },

    // Push Notifications
    { pattern: /cdn\.onesignal\.com|onesignal\.com/i, vendor: 'onesignal' },
    { pattern: /js\.pusher\.com|pusher\.com/i, vendor: 'pusher' },

    // Consent Management
    { pattern: /consent\.cookiebot\.com|cookiebot\.com/i, vendor: 'cookiebot' },
    { pattern: /cdn\.cookielaw\.org|onetrust\.com|optanon\.blob/i, vendor: 'onetrust' },
    { pattern: /sdk\.privacy-center\.org|didomi\.io/i, vendor: 'didomi' },
    { pattern: /consent\.trustarc\.com|trustarc\.com/i, vendor: 'trustarc' },
    { pattern: /client\.axept\.io|axeptio/i, vendor: 'axeptio' },

    // Reviews
    { pattern: /widget\.trustpilot\.com|trustpilot\.com/i, vendor: 'trustpilot' },
    { pattern: /staticw2\.yotpo\.com|yotpo\.com/i, vendor: 'yotpo' },
    { pattern: /cdn\.judge\.me|judge\.me/i, vendor: 'judge-me' },
    { pattern: /apps\.bazaarvoice\.com|bazaarvoice\.com/i, vendor: 'bazaarvoice' },

    // Payment
    { pattern: /js\.stripe\.com/i, vendor: 'stripe' },
    { pattern: /paypal\.com\/sdk|paypalobjects\.com/i, vendor: 'paypal' },

    // Support / Chat
    { pattern: /widget\.intercom\.io|intercom\.com/i, vendor: 'intercom' },
    { pattern: /static\.zdassets\.com|zendesk\.com/i, vendor: 'zendesk' },
    { pattern: /js\.driftt\.com/i, vendor: 'drift' },
    { pattern: /wchat\.freshchat\.com/i, vendor: 'freshchat' },
    { pattern: /cdn\.freshdesk\.com|freshdesk\.com/i, vendor: 'freshdesk' },
    { pattern: /client\.crisp\.chat|crisp\.chat/i, vendor: 'crisp' },
    { pattern: /cdn\.livechatinc\.com|livechat\.com/i, vendor: 'livechat' },
    { pattern: /code\.tidio\.co|tidio\.com/i, vendor: 'tidio' },
    { pattern: /embed\.tawk\.to|tawk\.to/i, vendor: 'tawk' },

    // CRM
    { pattern: /cdn\.pendo\.io|force\.com|salesforce\.com|salesforceliveagent\.com/i, vendor: 'salesforce' },
    { pattern: /cdn\.pipedrive\.com|pipedrive\.com/i, vendor: 'pipedrive' },

    // Security / Other
    { pattern: /www\.google\.com\/recaptcha|recaptcha\.net/i, vendor: 'recaptcha' },
    { pattern: /js\.hcaptcha\.com|hcaptcha\.com/i, vendor: 'hcaptcha' },
    { pattern: /browser\.sentry-cdn\.com|sentry\.io/i, vendor: 'sentry' },
    { pattern: /cdn\.logrocket\.io|logrocket\.com/i, vendor: 'logrocket' },
    { pattern: /edge\.fullstory\.com|fullstory\.com/i, vendor: 'fullstory' },
];

// Get risk assessment for a URL or script source
export function getVendorRisk(url: string): VendorRisk | null {
    for (const { pattern, vendor } of vendorPatterns) {
        if (pattern.test(url)) {
            return vendorRiskDatabase[vendor] || null;
        }
    }
    return null;
}

// Get risk level label
export function getRiskLabel(score: number): 'low' | 'medium' | 'high' | 'critical' {
    if (score <= 2) return 'low';
    if (score <= 5) return 'medium';
    if (score <= 7) return 'high';
    return 'critical';
}

// Get risk color for UI
export function getRiskColor(score: number): string {
    if (score <= 2) return '#22c55e'; // green
    if (score <= 5) return '#eab308'; // yellow
    if (score <= 7) return '#f97316'; // orange
    return '#ef4444'; // red
}
