export interface CountryData {
    slug: string;
    name: string;
    localName: string;
    flag: string;
    dpa: string;           // Data Protection Authority
    dpaUrl: string;
    localLaw: string;      // Local implementation of GDPR or equivalent
    language: string;
    population: string;
    fineExample?: string;
    fineAmount?: string;
    keyRequirements: string[];
    specificNotes: string;
    metaTitle: string;
    metaDescription: string;
}

export const countries: CountryData[] = [
    {
        slug: 'germany',
        name: 'Germany',
        localName: 'Deutschland',
        flag: '🇩🇪',
        dpa: 'Bundesbeauftragte für den Datenschutz und die Informationsfreiheit (BfDI)',
        dpaUrl: 'https://www.bfdi.bund.de/',
        localLaw: 'Bundesdatenschutzgesetz (BDSG)',
        language: 'German',
        population: '84 million',
        fineExample: 'H&M fined for employee surveillance',
        fineAmount: '€35.3 million',
        keyRequirements: [
            'Strict consent requirements — opt-in required before any tracking',
            'Works councils must be consulted on employee data processing',
            'Data Protection Officer (DPO) mandatory for companies with 20+ employees processing personal data',
            'TTDSG (Telekommunikation-Telemedien-Datenschutz-Gesetz) governs cookies and tracking',
            'Double opt-in required for email marketing',
            'Stricter rules for employee monitoring than EU baseline',
        ],
        specificNotes: 'Germany has 16 state-level DPAs in addition to the federal BfDI, making enforcement one of the strictest in Europe. German courts have been particularly aggressive on cookie consent enforcement, including issuing fines for Google Fonts loaded without consent.',
        metaTitle: 'GDPR Compliance for German Websites — BDSG & TTDSG Requirements',
        metaDescription: 'Check if your website meets German GDPR (DSGVO), BDSG, and TTDSG requirements. Free scanner for cookie consent, privacy policy, and data protection compliance in Germany.',
    },
    {
        slug: 'france',
        name: 'France',
        localName: 'France',
        flag: '🇫🇷',
        dpa: 'Commission Nationale de l\'Informatique et des Libertés (CNIL)',
        dpaUrl: 'https://www.cnil.fr/',
        localLaw: 'Loi Informatique et Libertés',
        language: 'French',
        population: '68 million',
        fineExample: 'Google fined for cookie consent violations',
        fineAmount: '€150 million',
        keyRequirements: [
            'CNIL cookie guidelines require explicit consent before non-essential cookies',
            'Refuse button must be as prominent as Accept button',
            'Cookie walls are generally prohibited',
            'Data Protection Officer mandatory for public bodies and large-scale processors',
            'Privacy impact assessments required for high-risk processing',
            'French language privacy policy required for French-facing websites',
        ],
        specificNotes: 'The CNIL is one of the most active DPAs in Europe, having issued major fines to Google (€150M), Amazon (€35M), and Meta (€60M). Their cookie guidelines published in 2020 are considered the gold standard for consent implementation.',
        metaTitle: 'GDPR Compliance for French Websites — CNIL Requirements & Scanner',
        metaDescription: 'Verify your website complies with French GDPR (RGPD) and CNIL cookie guidelines. Free audit for consent banners, privacy policy, and data protection in France.',
    },
    {
        slug: 'netherlands',
        name: 'Netherlands',
        localName: 'Nederland',
        flag: '🇳🇱',
        dpa: 'Autoriteit Persoonsgegevens (AP)',
        dpaUrl: 'https://autoriteitpersoonsgegevens.nl/',
        localLaw: 'Uitvoeringswet AVG (UAVG)',
        language: 'Dutch',
        population: '17.8 million',
        fineExample: 'Uber fined for data transfers to US',
        fineAmount: '€10 million',
        keyRequirements: [
            'Cookie consent must be freely given — no cookie walls',
            'BSN (social security number) processing heavily restricted',
            'Healthcare data requires extra safeguards',
            'DPO required for organizations processing sensitive data at scale',
            'Mandatory data breach notification within 72 hours',
            'Consent withdrawal must be as easy as giving consent',
        ],
        specificNotes: 'The Autoriteit Persoonsgegevens has been particularly strict on cross-border data transfers and Google Analytics usage. They issued guidance in 2022 warning that standard Google Analytics configurations violate GDPR.',
        metaTitle: 'GDPR Compliance for Dutch Websites — AVG Requirements & Scanner',
        metaDescription: 'Check your website against Dutch GDPR (AVG) requirements. Free compliance scanner for cookie consent, privacy policy, and Autoriteit Persoonsgegevens guidelines.',
    },
    {
        slug: 'spain',
        name: 'Spain',
        localName: 'España',
        flag: '🇪🇸',
        dpa: 'Agencia Española de Protección de Datos (AEPD)',
        dpaUrl: 'https://www.aepd.es/',
        localLaw: 'Ley Orgánica de Protección de Datos (LOPDGDD)',
        language: 'Spanish',
        population: '47 million',
        fineExample: 'CaixaBank fined for marketing violations',
        fineAmount: '€6 million',
        keyRequirements: [
            'Explicit consent needed for commercial emails (LSSI-CE)',
            'Cookie policy must be clearly visible',
            'DPO is mandatory for many organizations including healthcare, financial, and telecom',
            'National ID number (DNI) has special protections',
            'Data breach notifications to AEPD within 72 hours',
            'Right to digital disconnection for employees',
        ],
        specificNotes: 'Spain\'s LOPDGDD includes unique provisions like the right to digital disconnection and digital testament. The AEPD is among the most prolific enforcers in Europe, issuing hundreds of fines annually, often targeting SMEs as well as large corporations.',
        metaTitle: 'GDPR Compliance for Spanish Websites — LOPDGDD & AEPD Guide',
        metaDescription: 'Audit your website for Spanish GDPR (RGPD) and LOPDGDD compliance. Free scanner for cookie consent, datos personales protection, and AEPD requirements.',
    },
    {
        slug: 'italy',
        name: 'Italy',
        localName: 'Italia',
        flag: '🇮🇹',
        dpa: 'Garante per la protezione dei dati personali',
        dpaUrl: 'https://www.garanteprivacy.it/',
        localLaw: 'Codice della Privacy (D.Lgs. 196/2003, updated)',
        language: 'Italian',
        population: '59 million',
        fineExample: 'Clearview AI fined for facial recognition',
        fineAmount: '€20 million',
        keyRequirements: [
            'Cookie banner must allow granular category-level consent',
            'Scroll is NOT valid consent (ruled by Garante)',
            'Marketing requires prior specific consent',
            'Cookie policy must be separate from privacy policy',
            'DPO mandatory for public bodies and large-scale processors',
            'Italian-language privacy notice required for local users',
        ],
        specificNotes: 'Italy\'s Garante has issued detailed cookie guidelines requiring a two-layer approach: a short banner with essential info and a second layer with full cookie details and granular controls. Italy was among the first to ban ChatGPT temporarily over GDPR concerns.',
        metaTitle: 'GDPR Compliance for Italian Websites — Garante Privacy Requirements',
        metaDescription: 'Check your website against Italian GDPR and Garante per la Privacy requirements. Free audit for cookie consent, privacy policy, and data protection compliance in Italy.',
    },
    {
        slug: 'belgium',
        name: 'Belgium',
        localName: 'België / Belgique',
        flag: '🇧🇪',
        dpa: 'Gegevensbeschermingsautoriteit (GBA)',
        dpaUrl: 'https://www.gegevensbeschermingsautoriteit.be/',
        localLaw: 'Belgian Data Protection Act',
        language: 'Dutch, French, German',
        population: '11.6 million',
        fineExample: 'IAB Europe fined for TCF consent framework',
        fineAmount: '€250,000',
        keyRequirements: [
            'Strict interpretation of consent — pre-ticked boxes prohibited',
            'Cookie walls are considered non-compliant',
            'IAB TCF framework ruled insufficient by Belgian DPA',
            'DPO must be accessible to data subjects',
            'Data breach notification within 72 hours',
            'Enhanced protections for employee data',
        ],
        specificNotes: 'The Belgian DPA made headlines by ruling that the IAB Europe\'s Transparency and Consent Framework (TCF) violated GDPR, affecting the entire ad-tech industry across Europe. This ruling has major implications for programmatic advertising.',
        metaTitle: 'GDPR Compliance for Belgian Websites — GBA Requirements & Audit',
        metaDescription: 'Verify your website meets Belgian GDPR requirements and GBA guidelines. Free compliance scanner for cookie consent, IAB TCF, and data protection in Belgium.',
    },
    {
        slug: 'austria',
        name: 'Austria',
        localName: 'Österreich',
        flag: '🇦🇹',
        dpa: 'Datenschutzbehörde (DSB)',
        dpaUrl: 'https://www.dsb.gv.at/',
        localLaw: 'Datenschutzgesetz (DSG)',
        language: 'German',
        population: '9.1 million',
        fineExample: 'Austrian Post fined for profiling voters',
        fineAmount: '€18 million',
        keyRequirements: [
            'Google Analytics was ruled non-compliant by DSB in landmark 2022 decision',
            'Explicit consent required before any analytics tracking',
            'DPO required for regular and systematic monitoring at scale',
            'Must ensure EU-adequate data transfer mechanisms',
            'Cookie consent cannot be bundled with terms acceptance',
            'Data subjects can lodge complaints directly with DSB',
        ],
        specificNotes: 'Austria\'s DSB issued the groundbreaking ruling that Google Analytics violates GDPR due to US data transfers, following the Schrems II decision. This ruling cascaded across Europe and forced many websites to reconsider their analytics setup.',
        metaTitle: 'GDPR Compliance for Austrian Websites — DSG & DSB Requirements',
        metaDescription: 'Scan your website for Austrian GDPR (DSG) compliance. Free audit tool covering cookie consent, Google Analytics legality, and DSB requirements in Austria.',
    },
    {
        slug: 'poland',
        name: 'Poland',
        localName: 'Polska',
        flag: '🇵🇱',
        dpa: 'Urząd Ochrony Danych Osobowych (UODO)',
        dpaUrl: 'https://uodo.gov.pl/',
        localLaw: 'Polish Personal Data Protection Act',
        language: 'Polish',
        population: '38 million',
        fineExample: 'Morele.net fined for data breach',
        fineAmount: '€660,000',
        keyRequirements: [
            'Cookie consent must be informed and specific',
            'Polish-language privacy policy recommended for local sites',
            'DPO required per standard GDPR thresholds',
            'UODO can audit organizations on its own initiative',
            'Mandatory data breach register',
            'Employee data processing regulated by Labour Code',
        ],
        specificNotes: 'Poland has a large tech sector and growing e-commerce market. UODO has been increasingly active in enforcement, with a focus on SMEs and public sector organizations.',
        metaTitle: 'GDPR Compliance for Polish Websites — UODO Requirements & Scanner',
        metaDescription: 'Check your website against Polish GDPR requirements. Free compliance scanner for cookie consent, privacy policy, and UODO data protection guidelines in Poland.',
    },
    {
        slug: 'sweden',
        name: 'Sweden',
        localName: 'Sverige',
        flag: '🇸🇪',
        dpa: 'Integritetsskyddsmyndigheten (IMY)',
        dpaUrl: 'https://www.imy.se/',
        localLaw: 'Swedish Data Protection Act',
        language: 'Swedish',
        population: '10.5 million',
        fineExample: 'Spotify fined for DSAR response failures',
        fineAmount: '€5 million',
        keyRequirements: [
            'Google Analytics ruled non-compliant by IMY (2023)',
            'Cookie consent must be clear and unambiguous',
            'Strong emphasis on transparency in data processing',
            'DPO mandatory for public authorities',
            'Data breach notification includes both IMY and affected individuals',
            'Special rules for research and statistics processing',
        ],
        specificNotes: 'Sweden\'s IMY has been active in enforcing GDPR against Big Tech, particularly on analytics and cross-border data transfers. Several Swedish companies were fined for using Google Analytics in 2023.',
        metaTitle: 'GDPR Compliance for Swedish Websites — IMY Requirements & Audit',
        metaDescription: 'Verify your website meets Swedish GDPR requirements and IMY guidelines. Free scanner for cookie consent, Google Analytics compliance, and data protection in Sweden.',
    },
    {
        slug: 'denmark',
        name: 'Denmark',
        localName: 'Danmark',
        flag: '🇩🇰',
        dpa: 'Datatilsynet',
        dpaUrl: 'https://www.datatilsynet.dk/',
        localLaw: 'Danish Data Protection Act',
        language: 'Danish',
        population: '5.9 million',
        fineExample: 'IDdesign fined for excessive data retention',
        fineAmount: '€200,000',
        keyRequirements: [
            'Datatilsynet cookie guidance aligns with strict EU standards',
            'Consent required before setting non-essential cookies',
            'Data retention periods must be defined and documented',
            'DPO required for public bodies and large processors',
            'Strong focus on data minimization principle',
            'Cloud service providers must meet specific security standards',
        ],
        specificNotes: 'Denmark was one of the first countries to raise concerns about Google Workspace and Microsoft 365 in schools due to GDPR concerns. Datatilsynet has given detailed guidance on cloud services and international data transfers.',
        metaTitle: 'GDPR Compliance for Danish Websites — Datatilsynet Guide & Scanner',
        metaDescription: 'Audit your website for Danish GDPR compliance and Datatilsynet requirements. Free scanner for cookie consent, cloud services, and data protection in Denmark.',
    },
    {
        slug: 'finland',
        name: 'Finland',
        localName: 'Suomi',
        flag: '🇫🇮',
        dpa: 'Tietosuojavaltuutetun toimisto',
        dpaUrl: 'https://tietosuoja.fi/',
        localLaw: 'Finnish Data Protection Act',
        language: 'Finnish',
        population: '5.5 million',
        keyRequirements: [
            'Strict consent requirements for direct marketing',
            'Cookie consent must be freely given and specific',
            'DPO required for organizations specified by law',
            'Data breach notification within 72 hours to DPA',
            'Processing of personal identity codes is restricted',
            'Special provisions for health data processing',
        ],
        specificNotes: 'Finland has a strong focus on data security in healthcare and public sector. The Finnish DPA has been active in issuing guidance on AI and automated decision-making.',
        metaTitle: 'GDPR Compliance for Finnish Websites — Data Protection Scanner',
        metaDescription: 'Check your website for Finnish GDPR compliance. Free scanner for cookie consent, privacy policy, and data protection requirements in Finland.',
    },
    {
        slug: 'ireland',
        name: 'Ireland',
        localName: 'Éire',
        flag: '🇮🇪',
        dpa: 'Data Protection Commission (DPC)',
        dpaUrl: 'https://www.dataprotection.ie/',
        localLaw: 'Data Protection Act 2018',
        language: 'English',
        population: '5.1 million',
        fineExample: 'Meta (Instagram) fined for children\'s data handling',
        fineAmount: '€405 million',
        keyRequirements: [
            'Lead supervisory authority for most Big Tech companies (Google, Meta, Apple, TikTok)',
            'Cookie consent must be prior, informed, and specific',
            'Strong enforcement on children\'s data protection',
            'DPO required per standard GDPR criteria',
            'Data breach notifications within 72 hours',
            'Cross-border processing coordination with other EU DPAs',
        ],
        specificNotes: 'Ireland\'s DPC is the lead supervisory authority for most major tech companies headquartered in the EU. They have issued record fines including €1.2 billion to Meta for US data transfers — the largest GDPR fine ever.',
        metaTitle: 'GDPR Compliance for Irish Websites — DPC Requirements & Audit',
        metaDescription: 'Verify your website meets Irish GDPR requirements and Data Protection Commission guidelines. Free scanner for cookie consent and data protection in Ireland.',
    },
    {
        slug: 'portugal',
        name: 'Portugal',
        localName: 'Portugal',
        flag: '🇵🇹',
        dpa: 'Comissão Nacional de Proteção de Dados (CNPD)',
        dpaUrl: 'https://www.cnpd.pt/',
        localLaw: 'Lei de Execução do RGPD (Lei n.º 58/2019)',
        language: 'Portuguese',
        population: '10.3 million',
        keyRequirements: [
            'Cookie consent must be explicit and granular',
            'Portuguese-language privacy policy recommended',
            'DPO mandatory for public bodies and certain private organizations',
            'Special protections for genetic and biometric data',
            'Mandatory data breach notification to CNPD',
            'Employee consent generally not considered freely given',
        ],
        specificNotes: 'Portugal\'s CNPD has been particularly strict on video surveillance and biometric data processing. They also issued guidance warning against reliance on consent for employment data processing.',
        metaTitle: 'GDPR Compliance for Portuguese Websites — CNPD Requirements',
        metaDescription: 'Check your website against Portuguese GDPR (RGPD) requirements. Free compliance audit for cookie consent, privacy policy, and CNPD guidelines in Portugal.',
    },
    {
        slug: 'czech-republic',
        name: 'Czech Republic',
        localName: 'Česká republika',
        flag: '🇨🇿',
        dpa: 'Úřad pro ochranu osobních údajů (ÚOOÚ)',
        dpaUrl: 'https://www.uoou.cz/',
        localLaw: 'Act on Personal Data Processing',
        language: 'Czech',
        population: '10.8 million',
        keyRequirements: [
            'Cookie consent required before non-essential tracking',
            'DPO required for public bodies and large-scale processors',
            'Data breach notification within 72 hours',
            'Special provisions for journalist data processing',
            'Mandatory records of processing activities',
            'Consumer protection integrated with data protection',
        ],
        specificNotes: 'The Czech DPA has focused on public sector compliance and has issued guidelines specifically for small and medium enterprises on GDPR compliance.',
        metaTitle: 'GDPR Compliance for Czech Websites — ÚOOÚ Requirements & Scanner',
        metaDescription: 'Audit your website for Czech GDPR compliance. Free scanner for cookie consent, privacy policy, and ÚOOÚ data protection requirements in Czech Republic.',
    },
    {
        slug: 'romania',
        name: 'Romania',
        localName: 'România',
        flag: '🇷🇴',
        dpa: 'Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP)',
        dpaUrl: 'https://www.dataprotection.ro/',
        localLaw: 'Law no. 190/2018',
        language: 'Romanian',
        population: '19 million',
        keyRequirements: [
            'Cookie consent required with clear information',
            'DPO required per standard GDPR thresholds',
            'National ID (CNP) processing heavily regulated',
            'Data breach notification within 72 hours',
            'Health data requires additional safeguards',
            'Employee monitoring requires prior information',
        ],
        specificNotes: 'Romania has a growing tech sector and the DPA has been issuing increasing numbers of fines, particularly targeting companies that fail to respond to data subject requests.',
        metaTitle: 'GDPR Compliance for Romanian Websites — ANSPDCP Requirements',
        metaDescription: 'Check your website for Romanian GDPR compliance. Free scanner for cookie consent, privacy policy, and data protection requirements in Romania.',
    },
    {
        slug: 'hungary',
        name: 'Hungary',
        localName: 'Magyarország',
        flag: '🇭🇺',
        dpa: 'Nemzeti Adatvédelmi és Információszabadság Hatóság (NAIH)',
        dpaUrl: 'https://www.naih.hu/',
        localLaw: 'Hungarian Data Protection Act (Act CXII of 2011)',
        language: 'Hungarian',
        population: '9.7 million',
        keyRequirements: [
            'Cookie consent must be freely given and informed',
            'DPO required for organizations specified by law',
            'Data breach notification within 72 hours to NAIH',
            'Special provisions for political party data processing',
            'Employee data processing requires legal basis beyond consent',
            'Direct marketing requires prior opt-in consent',
        ],
        specificNotes: 'Hungary\'s NAIH has been active in enforcing GDPR particularly around direct marketing, telecom, and financial sector data processing.',
        metaTitle: 'GDPR Compliance for Hungarian Websites — NAIH Requirements',
        metaDescription: 'Verify your website meets Hungarian GDPR requirements. Free compliance scanner for cookie consent, privacy policy, and NAIH guidelines in Hungary.',
    },
    {
        slug: 'greece',
        name: 'Greece',
        localName: 'Ελλάδα',
        flag: '🇬🇷',
        dpa: 'Hellenic Data Protection Authority (HDPA)',
        dpaUrl: 'https://www.dpa.gr/',
        localLaw: 'Law 4624/2019',
        language: 'Greek',
        population: '10.4 million',
        keyRequirements: [
            'Cookie consent must be prior and specific',
            'DPO required per standard GDPR criteria',
            'Data breach notification within 72 hours',
            'Special protections for health and genetic data',
            'Video surveillance guidelines with strict transparency requirements',
            'Employee monitoring requires proportionality assessment',
        ],
        specificNotes: 'The HDPA has been particularly focused on video surveillance compliance and has issued detailed guidelines on CCTV use in public and private spaces.',
        metaTitle: 'GDPR Compliance for Greek Websites — HDPA Requirements & Scanner',
        metaDescription: 'Check your website for Greek GDPR compliance. Free audit for cookie consent, privacy policy, and Hellenic Data Protection Authority requirements.',
    },
    {
        slug: 'switzerland',
        name: 'Switzerland',
        localName: 'Schweiz / Suisse',
        flag: '🇨🇭',
        dpa: 'Federal Data Protection and Information Commissioner (FDPIC)',
        dpaUrl: 'https://www.edoeb.admin.ch/',
        localLaw: 'nDSG (New Data Protection Act, effective Sept 2023)',
        language: 'German, French, Italian',
        population: '8.8 million',
        keyRequirements: [
            'New nDSG took effect September 1, 2023 — significantly closer to GDPR',
            'Privacy by default required',
            'Data Protection Impact Assessments mandatory for high-risk processing',
            'Data breach notification within "as soon as possible" to FDPIC',
            'No consent required for processing based on legitimate interest (differs from GDPR)',
            'Criminal sanctions for individuals, not just fines for companies',
        ],
        specificNotes: 'Switzerland is not an EU member but its new nDSG aligns closely with GDPR. Key difference: violations can result in personal criminal liability for individuals (fines up to CHF 250,000), not just corporate penalties.',
        metaTitle: 'nDSG Compliance for Swiss Websites — Switzerland Data Protection Scanner',
        metaDescription: 'Verify your website meets Swiss nDSG (new Data Protection Act) requirements. Free scanner for cookie consent, privacy policy, and FDPIC compliance in Switzerland.',
    },
    {
        slug: 'united-kingdom',
        name: 'United Kingdom',
        localName: 'United Kingdom',
        flag: '🇬🇧',
        dpa: 'Information Commissioner\'s Office (ICO)',
        dpaUrl: 'https://ico.org.uk/',
        localLaw: 'UK GDPR + Data Protection Act 2018 + PECR',
        language: 'English',
        population: '67 million',
        fineExample: 'British Airways fined for data breach',
        fineAmount: '£20 million',
        keyRequirements: [
            'UK GDPR retained post-Brexit — largely mirrors EU GDPR',
            'PECR (Privacy and Electronic Communications Regulations) governs cookies',
            'ICO cookie guidance requires prior consent for non-essential cookies',
            'Legitimate interest assessment (LIA) must be documented',
            'Age-appropriate design code (Children\'s Code) for services targeting under-18s',
            'International data transfers require UK adequacy assessment or safeguards',
        ],
        specificNotes: 'Post-Brexit, the UK retained GDPR as domestic law (UK GDPR). The ICO has been shifting toward a more risk-based, innovation-friendly approach while maintaining core data protection standards. The UK has adequacy status from the EU until 2025.',
        metaTitle: 'UK GDPR Compliance for British Websites — ICO Requirements & Scanner',
        metaDescription: 'Audit your website for UK GDPR compliance and ICO requirements. Free scanner for PECR cookie consent, privacy policy, and data protection in the United Kingdom.',
    },
    {
        slug: 'norway',
        name: 'Norway',
        localName: 'Norge',
        flag: '🇳🇴',
        dpa: 'Datatilsynet',
        dpaUrl: 'https://www.datatilsynet.no/',
        localLaw: 'Norwegian Personal Data Act',
        language: 'Norwegian',
        population: '5.5 million',
        fineExample: 'Grindr fined for consent violations',
        fineAmount: '€6.5 million',
        keyRequirements: [
            'GDPR applies via EEA agreement',
            'Strict consent requirements for tracking and analytics',
            'DPO mandatory for public bodies',
            'Data breach notification within 72 hours',
            'Special provisions for research data',
            'Employee data processing has additional safeguards',
        ],
        specificNotes: 'Norway (via EEA) applies GDPR directly. The Norwegian Datatilsynet made international headlines by fining Grindr €6.5M for sharing user data with advertisers without valid consent. They are also active on AI regulation.',
        metaTitle: 'GDPR Compliance for Norwegian Websites — Datatilsynet Requirements',
        metaDescription: 'Check your website for Norwegian GDPR compliance. Free scanner for cookie consent, privacy policy, and Datatilsynet data protection guidelines in Norway.',
    },
    {
        slug: 'luxembourg',
        name: 'Luxembourg',
        localName: 'Lëtzebuerg',
        flag: '🇱🇺',
        dpa: 'Commission Nationale pour la Protection des Données (CNPD)',
        dpaUrl: 'https://cnpd.public.lu/',
        localLaw: 'Law of 1 August 2018',
        language: 'French, German, Luxembourgish',
        population: '660,000',
        fineExample: 'Amazon fined for ad targeting',
        fineAmount: '€746 million',
        keyRequirements: [
            'Home to Amazon EU — site of the largest GDPR fine ever (€746M)',
            'Cookie consent must be prior and informed',
            'DPO required for public bodies and large processors',
            'Data breach notification within 72 hours',
            'Special financial sector data protection rules',
            'Multilingual privacy notices recommended',
        ],
        specificNotes: 'Luxembourg\'s CNPD issued the record €746 million fine against Amazon for targeted advertising without proper consent — the largest GDPR fine to date. Many major tech companies have EU headquarters in Luxembourg.',
        metaTitle: 'GDPR Compliance for Luxembourg Websites — CNPD Requirements',
        metaDescription: 'Verify your website meets Luxembourg GDPR requirements. Free scanner for cookie consent, privacy policy, and CNPD data protection compliance in Luxembourg.',
    },
    {
        slug: 'croatia',
        name: 'Croatia',
        localName: 'Hrvatska',
        flag: '🇭🇷',
        dpa: 'Agencija za zaštitu osobnih podataka (AZOP)',
        dpaUrl: 'https://azop.hr/',
        localLaw: 'Croatian GDPR Implementation Act',
        language: 'Croatian',
        population: '3.9 million',
        keyRequirements: [
            'Cookie consent required per ePrivacy directive',
            'DPO required per standard GDPR criteria',
            'Data breach notification within 72 hours',
            'Special rules for video surveillance',
            'Croatian-language privacy notices recommended',
            'Growing enforcement focus on e-commerce',
        ],
        specificNotes: 'Croatia joined the Euro in 2023. AZOP has been increasing its enforcement activities, particularly targeting e-commerce sites and public sector organizations.',
        metaTitle: 'GDPR Compliance for Croatian Websites — AZOP Requirements',
        metaDescription: 'Check your website for Croatian GDPR compliance. Free scanner for cookie consent, privacy policy, and AZOP data protection requirements in Croatia.',
    },
    {
        slug: 'bulgaria',
        name: 'Bulgaria',
        localName: 'България',
        flag: '🇧🇬',
        dpa: 'Commission for Personal Data Protection (CPDP)',
        dpaUrl: 'https://www.cpdp.bg/',
        localLaw: 'Bulgarian Personal Data Protection Act',
        language: 'Bulgarian',
        population: '6.5 million',
        keyRequirements: [
            'Cookie consent required before non-essential tracking',
            'DPO required for public bodies and large-scale processors',
            'Data breach notification within 72 hours',
            'Special requirements for financial and health data',
            'Processing of EGN (personal ID number) restricted',
            'Mandatory records of processing activities',
        ],
        specificNotes: 'Bulgaria\'s CPDP has been focused on financial sector compliance and public administration data protection. They have issued guidance on employee monitoring and video surveillance.',
        metaTitle: 'GDPR Compliance for Bulgarian Websites — CPDP Requirements',
        metaDescription: 'Audit your website for Bulgarian GDPR compliance. Free scanner for cookie consent, privacy policy, and CPDP data protection requirements in Bulgaria.',
    },
];

export function getCountryBySlug(slug: string): CountryData | undefined {
    return countries.find(c => c.slug === slug);
}
